spring.application.name=jonzko-backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jackson.time-zone=America/Lima
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

mercadopago.access-token=${MP_ACCESS_TOKEN:}
app.frontend-url=${APP_FRONTEND_URL:http://localhost:4200}
# ==========================
# BREVO EMAIL
# ==========================
brevo.api.key=${BREVO_API_KEY:}
brevo.sender.email=${BREVO_SENDER_EMAIL:no-reply@jonzko.lat}
brevo.sender.name=${BREVO_SENDER_NAME:JONZKO SPORT}
# ==========================
# ADMIN NOTIFICACIONES
# ==========================
app.admin.email=jonathan.huaman18@gmail.com
app.admin.url=https://www.jonzko.lat/admin
# ==========================
# CLOUDINARY IMAGENES
# ==========================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

# ==========================
# JWT SEGURIDAD
# ==========================
jwt.secret=${JWT_SECRET:jonzko_super_secret_key_2026_para_firmar_tokens_jwt_seguro_123456789}
jwt.expiration-ms=86400000